### ISSUE TITLE
LNBank Payment does not get marked as settled

### ISSUE THREAD

**Issue by rolandschellhorn** [dennisreimann/btcpayserver#20] opened 2022-08-27 08:22 UTC
**Plugin**
LNBank

**Describe the bug**
After a while Lightning Payments via BTCPayServer APP get not marked as settled anymore.
Last possible payment was at 15:37 | Next payment at 18:26 went thru but did not got marked as settled.
The issue occurred bet 

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.6.9
- Plugin Name and Version   LNBank 1.2.3.0
- Deployment Method: Docker
- Browser: Chrome

**Logs (if applicable)**

info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Starting
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: Configuration:  Now listening on: http://0.0.0.0:49392
fail: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Checking pending transaction e3ed5284-7a9a-474a-821a-af56e0cdbfc1 failed: The HTTP status code of the response was not expected (500).
HTTP Response: 

{"code":2,"message":"waiting to start, RPC services not available","details":[]}

BTCPayServer.Lightning.LND.SwaggerException: The HTTP status code of the response was not expected (500).
   at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
   at BTCPayServer.Controllers.Greenfield.GreenfieldLightningNodeApiController.GetInvoice(String cryptoCode, String id, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs:line 238
   at BTCPayServer.Controllers.Greenfield.LocalBTCPayServerClient.GetLightningInvoice(String cryptoCode, String invoiceId, CancellationToken token) in /source/BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs:line 454
   at BTCPayServer.Plugins.LNbank.Services.BTCPayService.GetLightningInvoice(String invoiceId, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/BTCPayService.cs:line 52
   at BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher.CheckPendingTransaction(WalletService walletService, Transaction transaction, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/LightningInvoiceWatcher.cs:line 86
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
fail: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Checking pending transaction e3ed5284-7a9a-474a-821a-af56e0cdbfc1 failed: The HTTP status code of the response was not expected (500).
HTTP Response: 

{"code":2,"message":"waiting to start, RPC services not available","details":[]}

BTCPayServer.Lightning.LND.SwaggerException: The HTTP status code of the response was not expected (500).
   at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
   at BTCPayServer.Controllers.Greenfield.GreenfieldLightningNodeApiController.GetInvoice(String cryptoCode, String id, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs:line 238
   at BTCPayServer.Controllers.Greenfield.LocalBTCPayServerClient.GetLightningInvoice(String cryptoCode, String invoiceId, CancellationToken token) in /source/BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs:line 454
   at BTCPayServer.Plugins.LNbank.Services.BTCPayService.GetLightningInvoice(String invoiceId, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/BTCPayService.cs:line 52
   at BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher.CheckPendingTransaction(WalletService walletService, Transaction transaction, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/LightningInvoiceWatcher.cs:line 86
fail: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Checking pending transaction e3ed5284-7a9a-474a-821a-af56e0cdbfc1 failed: The HTTP status code of the response was not expected (500).
HTTP Response: 

{"code":2,"message":"wallet locked, unlock it to enable full RPC access","details":[]}

BTCPayServer.Lightning.LND.SwaggerException: The HTTP status code of the response was not expected (500).
   at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
   at BTCPayServer.Controllers.Greenfield.GreenfieldLightningNodeApiController.GetInvoice(String cryptoCode, String id, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs:line 238
   at BTCPayServer.Controllers.Greenfield.LocalBTCPayServerClient.GetLightningInvoice(String cryptoCode, String invoiceId, CancellationToken token) in /source/BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs:line 454
   at BTCPayServer.Plugins.LNbank.Services.BTCPayService.GetLightningInvoice(String invoiceId, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/BTCPayService.cs:line 52
   at BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher.CheckPendingTransaction(WalletService walletService, Transaction transaction, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/LightningInvoiceWatcher.cs:line 86
fail: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Checking pending transaction e3ed5284-7a9a-474a-821a-af56e0cdbfc1 failed: The HTTP status code of the response was not expected (500).
HTTP Response: 

{"code":2,"message":"the RPC server is in the process of starting up, but not yet ready to accept calls","details":[]}

BTCPayServer.Lightning.LND.SwaggerException: The HTTP status code of the response was not expected (500).
   at BTCPayServer.Lightning.LND.LndSwaggerClient.LookupInvoiceAsync(String r_hash_str, Byte[] r_hash, CancellationToken cancellationToken)
   at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetInvoice(String invoiceId, CancellationToken cancellation)
   at BTCPayServer.Controllers.Greenfield.GreenfieldLightningNodeApiController.GetInvoice(String cryptoCode, String id, CancellationToken cancellationToken) in /source/BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs:line 238
   at BTCPayServer.Controllers.Greenfield.LocalBTCPayServerClient.GetLightningInvoice(String cryptoCode, String invoiceId, CancellationToken token) in /source/BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs:line 454
   at BTCPayServer.Plugins.LNbank.Services.BTCPayService.GetLightningInvoice(String invoiceId, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/BTCPayService.cs:line 52
   at BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher.CheckPendingTransaction(WalletService walletService, Transaction transaction, CancellationToken cancellationToken) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/Services/LightningInvoiceWatcher.cs:line 86

**Comment by dennisreimann** [comment] 2022-08-27 08:56
See this part:

```
{"code":2,"message":"wallet locked, unlock it to enable full RPC access","details":[]}
````

The underlying LND wallet is locked. Can you unlock it or see the LND logs for the cause of it being locked?

**Comment by rolandschellhorn** [comment] 2022-08-27 10:09
I updated the bug description for a specific timeframe.

Here are the Logs at this time for RTL and LND:

LND:
2022-08-26 06:34:07.734 [WRN] CRTR: Attempt 8000 for payment 0fed7d7a8e… failed: IncorrectOrUnknownPaymentDetails(amt=220366000 mSAT, height=751080)@4
2022-08-26 06:34:07.767 [INF] CRTR: Payment 0fed7d7a8e… failed: final_outcome=incorrect_payment_details, raw_err=IncorrectOrUnknownPaymentDetails(amt=220366000 mSAT, height=751080)@4
2022-08-26 06:34:07.788 [INF] LOOP: 0fed7d Payment 0fed7d7a8e…: state=IN_FLIGHT, inflight_htlcs=0, inflight_amt=0 mSAT
2022-08-26 06:34:07.815 [ERR] CRTR: Payment 0fed7d7a8e… failed: incorrect_payment_details
2022-08-26 06:34:07.816 [INF] LOOP: 0fed7d Payment 0fed7d7a8e..: state=FAILED

2022-08-26 16:47:58.980 [WRN] DISC: ignoring remote ChannelAnnouncement for own channel
2022-08-26 16:56:44.515 [ERR] CRTR: unable to add channel: edge not found
2022-08-26 16:56:44.515 [ERR] DISC: unable to add channel: edge not found


2022-08-26 18:04:22.082 [WRN] CHBU: Replacing disk backup for ChannelPoint(..:0) w/ newer version
 2022-08-26 18:04:22.082 [WRN] CHBU: Replacing disk backup for ChannelPoint(..:1) w/ newer version
 2022-08-26 18:04:22.082 [WRN] CHBU: Replacing disk backup for ChannelPoint(..:1) w/ newer version
 2022-08-26 18:04:22.082 [WRN] CHBU: Replacing disk backup for ChannelPoint(..:0) w/ newer version
 2022-08-26 18:04:22.082 [WRN] CHBU: Replacing disk backup for ChannelPoint(..:0) w/ newer version
 2022-08-26 18:04:22.082 [WRN] CHBU: Replacing disk backup for ChannelPoint(..:1) w/ newer version
 2022-08-26 18:04:22.088 [INF] CHBU: Updating backup file at /root/.lnd/data/chain/bitcoin/mainnet/channel.backup
 

 2022-08-26 18:01:42.559 [INF] DISC: GossipSyncer(0217..): applying gossipFilter(start=0001-01-01 00:00:00 +0000 UTC, end=0001-01-01 00:00:00 +0000 UTC)
 2022-08-26 18:01:42.560 [INF] DISC: GossipSyncer(02f1..): applying gossipFilter(start=2022-08-26 18:01:42.560009914 +0000 UTC m=+92467.484938708, end=2158-10-03 00:29:57.560009914 +0000 UTC)
 2022-08-26 18:01:56.263 [INF] CRTR: Processed channels=0 updates=217 nodes=2 in last 1m0.00018675s
 2022-08-26 18:02:12.559 [INF] DISC: Broadcasting 335 new announcements in 18 sub batches
 2022-08-26 18:02:56.263 [INF] CRTR: Processed channels=0 updates=154 nodes=10 in last 59.999789203s
 2022-08-26 18:03:14.343 [INF] LOOPD: Received SIGINT (Ctrl+C).
 2022-08-26 18:03:14.343 [INF] LTND: Received terminated
 2022-08-26 18:03:14.343 [INF] LOOPD: Stopping gRPC server
 2022-08-26 18:03:14.343 [INF] LTND: Shutting down...
 2022-08-26 18:03:14.344 [INF] LTND: Gracefully shutting down.
 2022-08-26 18:03:14.345 [INF] NANN: Channel Status Manager shutting down
 2022-08-26 18:03:14.345 [INF] HSWC: HTLC Switch shutting down
 2022-08-26 18:03:14.345 [INF] NTFN: Cancelling epoch notification, epoch_id=6
 2022-08-26 18:03:14.345 [INF] NTFN: Cancelling epoch notification, epoch_id=3
 2022-08-26 18:03:14.345 [INF] HSWC: Removing channel link with ChannelID(85..)
 2022-08-26 18:03:14.345 [INF] HSWC: Removing channel link with ChannelID(60..)
 2022-08-26 18:03:14.345 [INF] HSWC: Removing channel link with ChannelID(da..)
 2022-08-26 18:03:14.345 [INF] HSWC: Removing channel link with ChannelID(e0..)
 2022-08-26 18:03:14.345 [INF] HSWC: Removing channel link with ChannelID(d0..)
 2022-08-26 18:03:14.345 [INF] HSWC: Removing channel link with ChannelID(e5..)
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(57..:0): stopping
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(f8..:0): stopping
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(57..0): exited
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(5c…:1): stopping
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(17..:0): stopping
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(5c..:1): exited
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(5d..:1): stopping
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(5c..:1): stopping
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(5c..:1): exited
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(f8..:0): exited
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(17..:0): exited
 2022-08-26 18:03:14.346 [INF] HSWC: ChannelLink(5d..:1): exited
 2022-08-26 18:03:14.360 [INF] HSWC: Onion processor shutting down
 2022-08-26 18:03:14.361 [INF] HSWC: Decaying hash log received shutdown request
 2022-08-26 18:03:14.361 [INF] NTFN: Cancelling epoch notification, epoch_id=8
 2022-08-26 18:03:14.361 [INF] INVC: InvoiceRegistry shutting down
 2022-08-26 18:03:14.361 [INF] NTFN: Cancelling epoch notification, epoch_id=7
 2022-08-26 18:03:14.361 [INF] INVC: Cancelling invoice subscription for client=2
 2022-08-26 18:03:14.428 [INF] LOOP: Swap client terminating
 2022-08-26 18:03:14.428 [INF] LOOP: Swap client terminated
 2022-08-26 18:03:14.428 [INF] LOOPD: Swap client stopped
 2022-08-26 18:03:14.428 [INF] LOOPD: Liquidity manager stopped
 2022-08-26 18:03:14.442 [INF] LOOPD: Stopping REST server
 2022-08-26 18:03:14.449 [INF] LOOPD: Daemon exited
 2022-08-26 18:03:14.470 [INF] CRTR: Channel Router shutting down
 2022-08-26 18:03:14.470 [INF] CRTR: FilteredChainView stopping
 2022-08-26 18:03:14.471 [ERR] DISC: router shutting down
 2022-08-26 18:03:14.471 [ERR] DISC: router shutting down
 2022-08-26 18:03:14.486 [ERR] RPCS: [/invoicesrpc.Invoices/SubscribeSingleInvoice]: subscription for invoice(pay_hash=6f4a07a9d2981a7dbc05d5d42e28ebfe71d06aa4ba99e72bf0817ecd21dafd69): context canceled

RTL:
[8/26/2022, 8:17:15 PM] ERROR: RTLConf => Reading Config Error: {"statusCode":500,"message":"Reading Config Error","error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/root/.lnd/lnd.conf"}}
[8/26/2022, 8:17:17 PM] ERROR: RTLConf => Reading Config Error: {"statusCode":500,"message":"Reading Config Error","error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/root/.lnd/lnd.conf"}}

**Comment by dennisreimann** [comment] 2022-08-27 15:59
Hmm, RTL cannot read the config, looks like something is messed up there too. Does `btcpay-restart.sh` help?

**Comment by rolandschellhorn** [comment] 2022-08-28 09:11
A restart works (always) but for how long.. I checked the RTL-Config.json and the lnd.conf - for me it looks fine. The rtl error occurs when I try to read it inside the rtl dashboard (Node Config > LND Config). I guess I should address this issue at RTL. Is updating rtl a thing that comes with btcpayserver or should I just update it myself? On the other hand this issue should not affect the lnbank behavior but it shows something wrong. What happens to all the lnbank wallets if I unistall the plugin an later install it again?

**Comment by dennisreimann** [comment] 2022-08-28 15:17
> What happens to all the lnbank wallets if I unistall the plugin an later install it again?

The database does not get deleted, so the data would persist. However, reinstalling won't fix your issue – the log messages you posted hinted at a locked LND wallet. LNbank cannot work if the underlying node's wallet is locked, so we must get to why that happened.

**Comment by rolandschellhorn** [comment] 2022-08-29 15:27
Everything still work for now. I guess we close it and I reopen - if it happens again and/or I find the problem/solution.

**Comment by dennisreimann** [comment] 2022-08-29 15:36
Please do so, ideally with the BTCPay Server Docker logs! Thanks for you help debugging!

**Closed** 2022-08-29 15:37 UTC
